services:
  web:
    image: ghcr.io/zozinnovations/zoz-website:latest
    container_name: zoz-website
    restart: unless-stopped
    networks:
      - web-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zoz.rule=Host(`zozinnovations.com`, `www.zozinnovations.com`)"
      - "traefik.http.routers.zoz.entrypoints=websecure"
      - "traefik.http.routers.zoz.tls.certresolver=myresolver"
      - "traefik.http.services.zoz.loadbalancer.server.port=80"

networks:
  web-network:
    external: true
